# Generated by Django 2.2.3 on 2019-07-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reference',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
