# Generated by Django 2.2.3 on 2019-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anony',
            field=models.TextField(default=None),
        ),
    ]
