# Generated by Django 2.2.3 on 2019-07-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190719_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lnglat',
        ),
    ]
