# Generated by Django 2.2.3 on 2019-08-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_auto_20190802_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ip',
            field=models.CharField(max_length=15),
        ),
    ]
