# Generated by Django 2.2.3 on 2019-08-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0004_gameuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameuser',
            old_name='sever_name',
            new_name='server_name',
        ),
        migrations.AlterUniqueTogether(
            name='gameuser',
            unique_together={('server_name', 'username')},
        ),
    ]
